// This file is generated by Vagebond\Runtype
// App\Http\Resources\BlogPostResource
export type BlogPostResourceType = {
id:number
title:string
slug:string
subtitle:string
description:string
content:string
published_at:string
}
// App\Http\Resources\ProjectResource
export type ProjectResourceType = {
id:number
title:string
slug:string
description:string
tags:TagResourceType[]
subtitle:string
content:string
started_at:string
created_at:string
updated_at:string
}
// App\Http\Resources\CommentResource
export type CommentResourceType = {
id:number
user:{name:string,avatar:string}
permissions:{edit:boolean,delete:boolean}
content:string
children:CommentResourceType[]
created_at:string
updated_at:string
}
// App\Http\Resources\TagResource
export type TagResourceType = {
title:string
}