// This file is generated by Vagebond\Runtype
// App\Http\Resources\BlogPostResource
export type BlogPostResourceType = {
id:number
title:string
slug:string
subtitle:string
description:string
banner:string
content:string
published_at:string
}
// App\Http\Resources\ProjectResource
export type ProjectResourceType = {
id:number
title:string
slug:string
description:string
subtitle:string
content:string
started_at:string
created_at:string
updated_at:string
}
