// This file is generated by Vagebond\Runtype
// App\Http\Resources\ProjectResource
export type ProjectResourceType = {
id:number
title:string
slug:string
subtitle:string
description:string
content:string
started_at:string
ended_at:string
created_at:string
updated_at:string
}